### ISSUE TITLE
Route not working correctly

### ISSUE THREAD

**Issue by Holofox** [tolo/stateful_books#1]
Hello! @tolo, i looked at the case of opening a page on top of tabs, but ran into a strange problem.

Diff: https://github.com/Holofox/stateful_books/commit/5895fc97276c9b98b0d5573033f91decd6e42c13

Steps to reproduce the issue:

1. `Sign in` -> `Authors` -> `Settings`.
2. Click on `Go directly to /book/0 (GoRouter)`
3. Click on `Authors`.

Expected result: The page with authors opens.
Actual result: The settings page opens.

This occurs when a page opened in the root context calls `context.go`

<img src="https://user-images.githubusercontent.com/19191492/235867341-b91c87b3-e344-4109-8f13-ebbd500a8337.gif" width=50% height=50%>

**Comment by tolo** [comment]
Good catch, thanks! I think this actually is a bug, or at least a scenario that isn't properly handled. I think I know what's going on, will try to address this as soon as possible.

**Comment by tolo** [comment]
Fixed as of flutter/packages@79a0c63389fb6a41039a4d25823a711ca2c8c944
