### ISSUE TITLE
Another exception was thrown: Assertion failed: file:///C:/flutter/flutter/packages/flutter/lib/src/rendering/object.dart:2283:14

### ISSUE THREAD

**Issue by anasmano** [tolo/stateful_books#2]
Hello @tolo,

First of all, I would like to thank you for your Repo because it was very helpful in developing my application. 

From the title above, I'm sure the issue I wrote about has nothing to do with the bug in your repo but has something to do with flutter. Why am I writing this issue in your repo because I'm not good at stringing words together to explain the bug explicitly to the f;utter dev team,

After cloning your repo, I modified it by adding a Bloc as management status, and changing the code of several files.

//A simple Bloc Added
```ruby
class CounterCubit extends Cubit<int> {
  CounterCubit() : super(0);
  
  void increment() => emit(state + 1);

  void decrement() => emit(state - 1);
}
```
The files I changed were 

lib/main.dart
```ruby
void main() => runApp(BlocProvider(
    create: (_) => CounterCubit(), lazy: false, child: Bookstore()));
    ...............
```

And in _guard function

```ruby
String? _guard(BuildContext context, GoRouterState state) {
    final bool signedIn = _auth.signedIn;
    final bool signingIn = state.matchedLocation == '/signin';

    // Go to /signin if the user is not signed in
    if (!signedIn && !signingIn) {
      return '/signin';
    }
    // Go to /books if the user is signed in and tries to go to /signin.
    else if (signedIn && signingIn) {
      return '/books/popular/1';  // **this is that I modified**
    }

    // no redirect
    return null;
  }

```

lib/src/screens/scaffold.dart

Adding a Floating Action Button

```ruby
AdaptiveNavigationScaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            context.read<CounterCubit>().increment();
          },
        ),
        backgroundColor: Colors.green,
          child: const Icon(Icons.navigation),
        ),      
        ...................


```
lib/src/screens/books.dart
```ruby
Scaffold(
        appBar: AppBar(
          title: BlocBuilder<CounterCubit, int>(
            builder: (context, state) {
              debugPrint('State Value Is $state');
              return Text('Books Counter $state');
            },
          ),
          ......................
```

Steps to reproduce the issue:

1. Sign in -> Authors 
2. Click On the Floating Action Button ( To increase counter on the  AppBar Title Text in lib/src/screens/books.dart file)
3. Click On Books

Expected result: The page `Books` remains as after signing in.

Actual result: The `Books` page turns into a white screen.
This occurs when pressing the Floating Action Button  and at the same time in debug  console the message 'Another exception has been thrown: (as title above)

**Note : 
This issue just appeared in debugging mode. In release mode it runs well. 
If you just write in the AppBar Title Text (in lib/screens/books.dart file) without $state, it will run well.**

Thank you in advance for your attention, hopefully this can help find a solution.

Regards.

**Comment by anasmano** [comment]
The Added Exception
```
EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Text("Books Counter 1", dependencies:
[DefaultSelectionStyle, DefaultTextStyle, MediaQuery]):

Assertion failed: file:///C:/flutter/flutter/packages/flutter/lib/src/rendering/object.dart:2283:14
_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()
is not true

The relevant error-causing widget was:
  Text Text:file:///C:/Users/User/Desktop/stateful_books-main-ori/lib/src/screens/books.dart:66:26

```

**Comment by tolo** [comment]
Sorry for the late reply - glad you found the repo helpful 😊 

Haven't worked all that much with Bloc, so I'm afraid I can't help you with this particular problem. However, the repo is now updated to use a much more simple and pragmatic (but still powerful) state management library, based around ChangeNotifier/ValueNotifier: [result_notifier](https://pub.dev/packages/result_notifier). I can recommend having a look 😊
